### ISSUE TITLE
Go through Tango with Django

### ISSUE THREAD

**Issue by cpgillem** [ccowmu/whatistheplan.com#11]
We all need to go through that tutorial
http://www.tangowithdjango.com/book17/index.html

**Comment by dyladan** [comment]
this is not really an 'issue'. this is more of something you'd put in a README under a 'development' heading. I made a basic README on a new branch not yet merged into master. Please read through it and let me know what you think. I will leave this issue open for you to close in case you disagree with my methodology.

https://github.com/ccowmu/whatistheplan.com/blob/readme/README.md

edit: closing issue. reopen if you disagree
