### ISSUE TITLE
Decide on standard tab width in source files

### ISSUE THREAD

**Issue by cpgillem** [ccowmu/whatistheplan.com#12]
Oh, python

Our most practical choices are:
4 spaces (that's what cpg likes and has in his vimrc)
tab characters
2 spaces
8 spaces

If you want to do something weird like 7 spaces we can discuss it, but we'll probably laugh at you.

**Comment by dyladan** [comment]
All python projects should be formatted according to the PEP8 standard which specifies that indentation should be 4 spaces. This not only helps with readability, but developers familiar with python will already be familiar with PEP8. This issue can be reopened if someone has a good reason why we should not follow PEP8 standard.

edit:
link for clarification
https://www.python.org/dev/peps/pep-0008/
