### ISSUE TITLE
Setup Vagrant VM for the repo.

### ISSUE THREAD

**Issue by cpgillem** [ccowmu/whatistheplan.com#2]
I'll make us a vagrant system that sets up Django, etc. for us to test.

**Comment by dyladan** [comment]
it might make it a lot simpler if you just used virtualenv. All python modules would be boxed and you wouldn't have to worry about the computational/administrative overhead of managing a dev VM environment. Just food for thought.

**Comment by cpgillem** [comment]
Vagrant's something I've used for PHP development with a database backend when I was learning about that. We can definitely use something simpler.

EDIT: s/similar/simpler

**Comment by dyladan** [comment]
vagrant is good for a lot of things, but i've usually found that lowering the barrier to entry is A Good Thing. Pretty much any python developer will have heard of virtualenv and you can version dependencies. The only thing is the database, but that can be solved by using sqlite in development and swapping over to a full database for production. This is one of the things that the ORM in django does very well.

**Comment by chrissphinx** [comment]
closed by #44
