### ISSUE TITLE
Add Facebook, Twitter, and Flickr social links

### ISSUE THREAD

**Issue by cpgillem** [ccowmu/whatistheplan.com#29]
These can be wherever. Just something that'll eventually need to be done.

**Comment by dyladan** [comment]
already have some social icons in the bottom right corner so thats probably the place to put them. @rhinoceraptor did the social links we already have so he's probably the guy to do this.

**Comment by dyladan** [comment]
@rhinoceraptor when you close an issue please make note of why it is being closed.

This issue was fixed in f37298e
